omc/src/main/java/com/hotsix/omc/controller/StoreController.java, omc/src/main/java/com/hotsix/omc/repository/StoreRepository.java, omc/src/main/java/com/hotsix/omc/service/StoreService.java, omc/src/main/java/com/hotsix/omc/service/StoreServiceImpl.java
- Store Controller에 deleteStore 추가하였습니다.
- StoreRepository 추가하였습니다.
- StoreService interface 추가하였습니다.
- Service에 findById로 deleteStore기능 추가하였습니다.
지라 백로그에 OMC-008 (Seller) 업체 관리 (본인 등록 업체 정보변경, 삭제)에서 삭제부분만 구현 됐구요,
본인 등록 업체 정보변경 부분은 휘성님께서 진행 해주기로 하셨습니다.
=> Feat#005 : deleteStore

omc/src/main/java/com/hotsix/omc/controller/CustomerController.java, omc/src/main/java/com/hotsix/omc/domain/form/customer/CustomerDeleteForm.java, omc/src/main/java/com/hotsix/omc/service/CustomerService.java
Changes
---
id에 해당하는 회원정보 삭제 구현
=> feat#006:delete_customer

omc/src/main/java/com/hotsix/omc/controller/SellerController.java, omc/src/main/java/com/hotsix/omc/controller/StoreController.java, omc/src/main/java/com/hotsix/omc/repository/StoreRepository.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/main/java/com/hotsix/omc/service/SellerServiceImpl.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceImplTest.java, omc/src/test/scratch/scratch_seller.http
Changes
---
- Seller id를 통한 업체 조회 서비스 구현
-
=> feat. 019-STORE-INFO

omc/src/main/java/com/hotsix/omc/controller/ReservationController.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationRequestDto.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationResponseDto.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationStoreResponseDto.java, omc/src/main/java/com/hotsix/omc/domain/entity/Reservation.java, omc/src/main/java/com/hotsix/omc/repository/ReservationRepository.java, omc/src/main/java/com/hotsix/omc/service/ReservationService.java
=> feat#027_Customer_Reserve

omc/src/main/java/com/hotsix/omc/controller/KakaoLoginController.java, omc/src/main/java/com/hotsix/omc/service/KakaoLoginService.java, omc/src/main/java/com/hotsix/omc/service/kakaoLoginServiceImpl.java
Changes
---
1. 정보를 가져오고 db에 넣는것까지 구현
2. access token 주입시 db에 카카오 정보 저장
=> feat. 005-KAKAO_API

omc/src/main/java/com/hotsix/omc/controller/ReservationController.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationRequestDto.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationResponseDto.java, omc/src/main/java/com/hotsix/omc/domain/dto/ReservationStoreResponseDto.java, omc/src/main/java/com/hotsix/omc/domain/entity/Reservation.java, omc/src/main/java/com/hotsix/omc/repository/ReservationRepository.java, omc/src/main/java/com/hotsix/omc/service/ReservationService.java
=> Feat#027_Customer_GetReserve

omc/src/test/java/com/hotsix/omc/service/service/CustomerSignupTest.java, omc/src/test/java/com/hotsix/omc/service/service/SellerSignupTest.java
---
Customer 와 Seller 의 회원가입 테스트 코드를 작성하였읍니다.
=> 고객, 셀러 회원가입 테스트 코드 작성

omc/build.gradle, omc/src/test/java/com/hotsix/omc/controller/CustomerSignupTest.java, omc/src/test/java/com/hotsix/omc/controller/SellerSignupTest.java
=> 고객, 셀러 회원가입 컨트롤러 테스트 코드 작성

omc/src/main/java/com/hotsix/omc/controller/SellerReservationController.java, omc/src/main/java/com/hotsix/omc/repository/ReservationRepository.java, omc/src/main/java/com/hotsix/omc/service/SellerReservationService.java, omc/src/test/java/com/hotsix/omc/service/SellerReservationServiceTest.java, omc/src/test/scratch/scratch_seller_reservation.http
Changes
---
- Seller reservation 예약 조회
- test코드 작성 완료
=> feat. 028-seller-reservation

omc/src/main/java/com/hotsix/omc/controller/CustomerController.java, omc/src/main/java/com/hotsix/omc/domain/entity/Customer.java, omc/src/main/java/com/hotsix/omc/domain/entity/Review.java, omc/src/main/java/com/hotsix/omc/domain/form/customer/CustomerReviewForm.java, omc/src/main/java/com/hotsix/omc/domain/form/customer/CustomerUpdateForm.java, omc/src/main/java/com/hotsix/omc/repository/ReviewRepository.java, omc/src/main/java/com/hotsix/omc/repository/StoreRepository.java, omc/src/main/java/com/hotsix/omc/service/CustomerService.java, omc/src/main/java/com/hotsix/omc/service/ReviewService.java, omc/src/test/java/com/hotsix/omc/service/CustomerReviewTest.java, omc/src/test/java/com/hotsix/omc/service/CustomerUpdateDeleteTest.java
Changes
---
기존에 pr한 회원 수정, 탈퇴, 리뷰남기기 기능 merge 시 conflict 날거같아서 하나로 합쳐서 올립니다.
회원 수정, 탈퇴, 리뷰남기기 테스트 코드 구현하였습니다.
Background
---
기존 pr은 헷갈릴수 있으니 closed 하겠습니다.
=> feat:customer_update_delete_review

omc/src/main/java/com/hotsix/omc/controller/CustomerController.java, omc/src/main/java/com/hotsix/omc/controller/StoreController.java, omc/src/main/java/com/hotsix/omc/domain/entity/Review.java, omc/src/main/java/com/hotsix/omc/domain/form/store/StoreReviewForm.java, omc/src/main/java/com/hotsix/omc/exception/ErrorCode.java, omc/src/main/java/com/hotsix/omc/repository/ReviewRepository.java, omc/src/main/java/com/hotsix/omc/service/ReviewService.java, omc/src/test/java/com/hotsix/omc/service/CustomerReviewTest.java, omc/src/test/java/com/hotsix/omc/service/StoreReviewTest.java
Changes
---
1. 고객 리뷰 등록
2. 고객 리뷰 수정
3. 고객 리뷰 삭제
4. 업체 리뷰 답변 등록
5. 업체 리뷰 조회
6. 테스트코드 작성
=> feat:customer,seller Review

omc/src/main/java/com/hotsix/omc/controller/KakaoLoginController.java, omc/src/main/java/com/hotsix/omc/service/KakaoLoginService.java, omc/src/main/java/com/hotsix/omc/service/kakaoLoginServiceImpl.java
Changes
---
1. build.gradle에 implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.6'
implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.14' 추가
2. 카카오 로그아웃 구현
=> refactor:kakao

omc/build.gradle, omc/src/main/java/com/hotsix/omc/Scraper/CarNewsScraper.java, omc/src/main/java/com/hotsix/omc/controller/CarNewsController.java
- Class CarNewsController
- Get메소드 getCarNews 구현
- Class CarNewsScraper 
- getCarNews메소드 구현
- build.gradle 
- jsoup 1.7.2 추가
=> feat#046_CarNewsScraper

omc/build.gradle, omc/src/main/java/com/hotsix/omc/controller/StoreController.java, omc/src/main/java/com/hotsix/omc/domain/entity/Address.java, omc/src/main/java/com/hotsix/omc/domain/entity/Store.java, omc/src/main/java/com/hotsix/omc/service/KakaoMapsService.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceTest.java, omc/src/test/scratch/scratch_seller.http
Changes
---
- 카카오 맵 API, 업체의 등록된 주소 이용하여 DB에 경도, 위도 저장
=> 054-STORE-LATLNT

omc/build.gradle, omc/src/main/java/com/hotsix/omc/controller/SearchController.java, omc/src/main/java/com/hotsix/omc/controller/StoreController.java, omc/src/main/java/com/hotsix/omc/domain/entity/Address.java, omc/src/main/java/com/hotsix/omc/domain/entity/Store.java, omc/src/main/java/com/hotsix/omc/repository/StoreRepository.java, omc/src/main/java/com/hotsix/omc/service/KakaoMapsService.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/main/java/com/hotsix/omc/service/StoreSearchService.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceTest.java, omc/src/test/java/com/hotsix/omc/service/StoreSearchServiceTest.java, omc/src/test/scratch/scratch_seller.http
Changes
---
- 현재 위치 기반으로 가장 가까운 가게 5개 조회 기능 구현
- 테스트 코드
=> 054 search by location

omc/src/main/java/com/hotsix/omc/exception/ErrorCode.java
Error Code 에서 나는 conflict 수정했습니다.
아마 머지전에는 풀하셨을 때 notification 부분에서 conflict 가 날 것입니다.
=> refactor#51 : conflict

omc/src/main/java/com/hotsix/omc/service/KakaoMapsService.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/test/java/com/hotsix/omc/service/KakaoMapsServiceTest.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceTest.java
Changes
---
- Json String 가져오는 부분과 파싱 부분 분리
- 테스트 코드 작성
=> 054-STORE-SAVE-GEOCODE

omc/src/main/java/com/hotsix/omc/controller/SellerReservationController.java, omc/src/main/java/com/hotsix/omc/service/KakaoMapsService.java, omc/src/main/java/com/hotsix/omc/service/SellerReservationService.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/test/java/com/hotsix/omc/service/KakaoMapsServiceTest.java, omc/src/test/java/com/hotsix/omc/service/SellerReservationServiceTest.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceTest.java
=> 028 seller reservation

omc/build.gradle, omc/src/main/java/com/hotsix/omc/OmcApplication.java, omc/src/main/java/com/hotsix/omc/s3/controller/UploadController.java, omc/src/main/java/com/hotsix/omc/s3/dto/FileDetailDto.java, omc/src/main/java/com/hotsix/omc/s3/service/FileUploadService.java, omc/src/main/java/com/hotsix/omc/s3/storage/AmazonS3ResourceStorage.java, omc/src/main/java/com/hotsix/omc/s3/util/MultipartUtil.java
- FileDetailDto
- FileUploadService
- AmazoneS3ResourceStorage
- MultipartUtil
- OmcApplicatin에 static 추가(서비스 실행에서 지연발생시 예외 방지 옵션)
=> feat#066_amazon_s3_uploader

omc/Dockerfile, omc/build.gradle, omc/src/main/java/com/hotsix/omc/config/WebConfig.java, omc/src/main/java/com/hotsix/omc/controller/HelloController.java
Changes
---
1. cors 에러 해결위한 WebConfig 작성 -> CORS 에러 해결
2. Dockerfile 첨부
3. dependency 추가
=> bug:deploy

omc/src/main/java/com/hotsix/omc/s3/storage/AmazonS3ResourceStorage.java
=> refactor#067_store_method

omc/src/main/java/com/hotsix/omc/service/KakaoMapsService.java, omc/src/main/java/com/hotsix/omc/service/SellerService.java, omc/src/test/java/com/hotsix/omc/service/KakaoMapsServiceTest.java, omc/src/test/java/com/hotsix/omc/service/SellerServiceTest.java
Changes
---
- parsing 에러 수정 - latitude, longitude 타입 에러
=> 054 store geocode

omc/src/main/java/com/hotsix/omc/controller/ReservationController.java, omc/src/main/java/com/hotsix/omc/s3/controller/UploadController.java, omc/src/main/java/com/hotsix/omc/s3/service/FileUploadService.java, omc/src/main/java/com/hotsix/omc/s3/util/MultipartUtil.java
=> Refactor#066_s3_pakage_path
